language: node_js
node_js:
- '4'
script:
- npm run test
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_cb1b65bfda52_key -iv $encrypted_cb1b65bfda52_iv
  -in travis_deploy.enc -out travis_deploy -d
- chmod 600 travis_deploy
- cp travis_deploy ~/.ssh/id_rsa
after_success:
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/travis_deploy
- git remote add deploy git@54.238.161.17:/opt/git/babyMoveCounter.git
- git push deploy
- yes